apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-config-ns-sa
  namespace: platform-config
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-config-ns-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["carto.run"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-config-ns-role-binding
subjects:
- kind: ServiceAccount
  name: platform-config-ns-sa
  namespace: platform-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-config-ns-role

